1. Write a NumPy program to reverse an array (first element becomes last). 

In [ ]:
import numpy as np
x = np.arange(12, 38)

print(x)

x = x[::-1]
print(x)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


2. Write a NumPy program to extract all odd numbers from an array.

In [ ]:
a = np.array([1,2,3,4,5,6,6,7,7,8,9])
a[a % 2 == 1]

array([1, 3, 5, 7, 7, 9])

 3. Write a NumPy program to create a 2d array with 1 on the border and 0 inside. 

In [ ]:
x = np.ones((5,5))

print(x)

x[1:-1,1:-1] = 0
print(x)

4. Write a NumPy program to append values to the end of an array. 

In [ ]:
x = [10, 20, 30]

print(x)
x = np.append(x, [[40, 50, 60], [70, 80, 90]])

print(x)

[10, 20, 30]
[10 20 30 40 50 60 70 80 90]


5. Write a NumPy program to compute the median of flattened given array. 

In [ ]:
x = np.arange(12).reshape((2, 6))

print(x)
r1 =  np.median(x)

print(r1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
5.5


6. Write a NumPy program to find the most frequent value in an array. 

In [ ]:
x = np.random.randint(0, 10, 40)

print(x)

print(np.bincount(x).argmax())

[5 3 3 9 6 2 0 3 0 7 2 1 7 1 9 5 4 4 3 1 0 5 4 6 2 2 5 8 4 4 6 9 1 1 1 9 2
 0 6 7]
1


7. Write a NumPy program to check two random arrays are equal or not 

In [ ]:
x = np.random.randint(0,2,6)

print(x)
y = np.random.randint(0,2,6)

print(y)

array_equal = np.allclose(x, y)
print(array_equal)

[0 0 1 1 0 1]
[0 1 1 0 0 0]
False


8. Write a NumPy program to get the powers of an array values element-wise. 

In [ ]:
x = np.arange(7)

print(x)

print(np.power(x, 3))

[0 1 2 3 4 5 6]
[  0   1   8  27  64 125 216]


9. Write a NumPy program to add, subtract, multiply, divide arguments element-wise. 

In [ ]:
print(np.add(1.0, 4.0))

print(np.subtract(1.0, 4.0))

print(np.multiply(1.0, 4.0))

print(np.divide(1.0, 4.0))

10. Write a NumPy program to compute the multiplication of two given matrixes. 

In [ ]:
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]

print(p)
print(q)
result1 = np.dot(p, q)

print(result1)

[[1, 0], [0, 1]]
[[1, 2], [3, 4]]
[[1 2]
 [3 4]]


11. Write a NumPy program to replace all odd numbers in arr with -1 

In [ ]:
a = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]) 
 
o = (a%2 == 1) 
a[o] = -1 
print(a)

[-1  2 -1  4 -1  6 -1  8 -1 10]


12. Replace all odd numbers in arr with -1 without changing arr 

In [ ]:
a = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]) 
 
o = (a%2 == 1) 
a[o] = -1 
print(a)

[-1  2 -1  4 -1  6 -1  8 -1 10]


13. Convert a 1D array to a 2D array with 2 rows 

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr_2d = np.reshape(arr, (2, 5))
print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


14. Write a numpy program to swap two columns in a 2d numpy array? 

In [ ]:
a = np.arange(12).reshape(4, 3)

print(a)

a[:, [2, 0]] = a[:, [0, 2]]

print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 2  1  0]
 [ 5  4  3]
 [ 8  7  6]
 [11 10  9]]


15. Write a numpy program to swap two rows in a 2d numpy array?

In [ ]:
a = np.arange(12).reshape(4, 3)

print(a)

a[[0, 2]] = a[[2, 0]]

print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 6  7  8]
 [ 3  4  5]
 [ 0  1  2]
 [ 9 10 11]]


16. Write a numpy program to reverse the rows of a 2D array? 

In [ ]:
n = np.array([[[1, 2, 3, 4],[0, 1, 3, 4],[90, 91, 93, 94],[5, 0, 3, 2]]])

print(n)

n1 = print(n[::-1, ::-1])


[[[ 1  2  3  4]
  [ 0  1  3  4]
  [90 91 93 94]
  [ 5  0  3  2]]]
[[[ 5  0  3  2]
  [90 91 93 94]
  [ 0  1  3  4]
  [ 1  2  3  4]]]


17. Write a numpy program to reverse the columns of a 2D array?

In [ ]:
arr2D = np.array([[11, 12, 13, 11], [21, 22, 23, 24], [31, 32, 33, 34]])

print(arr2D)

reversedArr = np.flip(arr2D, axis=1)

print(reversedArr)

[[11 12 13 11]
 [21 22 23 24]
 [31 32 33 34]]
[[11 13 12 11]
 [24 23 22 21]
 [34 33 32 31]]
