1. Write a NumPy program to get the numpy version and show numpy build configuration. 

In [ ]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


2. Write a NumPy program to get help on the add function.

In [ ]:
print(np.info(np.add))



None


NameError: ignored

3. Write a NumPy program to test whether none of the elements of a given array is zero.

In [ ]:
x = np.array([1, 2, 3, 4])

print(x)

print(np.all(x))
x = np.array([0, 1, 2, 3])

print(x)

print(np.all(x))

[1 2 3 4]
True
[0 1 2 3]
False


4. Write a NumPy program to test if any of the elements of a given array is non-zero. 

In [ ]:
x = np.array([1, 0, 0, 0])

print(x)

print(np.any(x))
x = np.array([0, 0, 0, 0])

print(x)

print(np.any(x))

Original array:
[1 0 0 0]
Test whether any of the elements of a given array is non-zero:
True
Original array:
[0 0 0 0]
Test whether any of the elements of a given array is non-zero:
False


5. Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a  Number). 

In [ ]:
a = np.array([1, 0, np.nan, np.inf])

print(a)

print(np.isfinite(a))

Original array
[ 1.  0. nan inf]
Test a given array element-wise for finiteness :
[ True  True False False]


6. Write a NumPy program to test element-wise for positive or negative infinity. 

In [ ]:
a = np.array([1, 0, np.nan, np.inf])

print(a)

print(np.isinf(a))

Original array
[ 1.  0. nan inf]
Test element-wise for positive or negative infinity:
[False False False  True]


7. Write a NumPy program to test element-wise for NaN of a given array. 

In [ ]:
a = np.array([1, 0, np.nan, np.inf])

print(a)

print(np.isnan(a))

Original array
[ 1.  0. nan inf]
Test element-wise for NaN:
[False False  True False]


8. Write a NumPy program to test element-wise for complex number, real number of a given array.  Also test if a given number is a scalar type or not. 

In [ ]:
a = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])

print(a)

print(np.iscomplex(a))

print(np.isreal(a))

print(np.isscalar(3.1))
print(np.isscalar([3.1]))

Original array
[1. +1.j 1. +0.j 4.5+0.j 3. +0.j 2. +0.j 0. +2.j]
Checking for complex number:
[ True False False False False  True]
Checking for real number:
[False  True  True  True  True False]
Checking for scalar type:
True
False


9. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and  less_equal) of two given arrays. 

In [ ]:
x = np.array([3, 5])
y = np.array([2, 5])

print(x)
print(y)

print(np.greater(x, y))

print(np.greater_equal(x, y))

print(np.less(x, y))

print(np.less_equal(x, y))

Original numbers:
[3 5]
[2 5]
Comparison - greater
[ True False]
Comparison - greater_equal
[ True  True]
Comparison - less
[False False]
Comparison - less_equal
[False  True]


10. Write a NumPy program to create an array of 10 zeros, an array of 10 ones, and an array of 10  fives. 

In [ ]:
array=np.zeros(10)

print(array)
array=np.ones(10)

print(array)
array=np.ones(10)*5

print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


11. Write a NumPy program to create an array of the integers from 30 to70. 

In [ ]:
array=np.arange(30,71)

print(array)

Array of the integers from 30 to70
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


12. Write a NumPy program to create an array of all the even integers from 30 to 70. 

In [ ]:
array=np.arange(30,71,2)

print(array)

Array of all the even integers from 30 to 70
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


13. Write a NumPy program to create a 3x3 identity matrix. 

In [ ]:
a=np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. Write a NumPy program to generate a random number between 0 and 1. 

In [ ]:
rand_num = np.random.normal(0,1,1)
print(rand_num)

[1.28956032]


15. Write a NumPy program to generate an array of 15 random numbers from a standard normal  distribution. 

In [ ]:
rand_num = np.random.normal(0,1,15)
print(rand_num)

[ 2.17698653  0.46501601  0.70606199  0.17611228  0.48331627 -2.4937098
  1.16998865 -0.07789246  0.54257212 -0.74696954 -0.33596875  0.28574831
 -1.66497638  0.62868337  0.37859194]


16. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values  except the first and last.

In [ ]:
a = np.arange(15,55)
print(a)
print(a[1:-1])

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


17. Write a NumPy program to create a vector of length 10 with values evenly distributed between 5  and 50. 

In [ ]:
a = np.linspace(10, 49, 5)
print(a)

[10.   19.75 29.5  39.25 49.  ]


18. Write a NumPy program to multiply the values of two given vectors

In [ ]:
x = np.array([1, 8, 3, 5])

print(x)
y= np.random.randint(0, 11, 4)

print(y)
result = x * y

print(result)

Vector-1
[1 8 3 5]
Vector-2
[ 1 10  2  7]
Multiply the values of two said vectors:
[ 1 80  6 35]


19. Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.

In [ ]:
m= np.arange(10,22).reshape((3, 4))
print(m)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


20. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to  1, 2, 3, 4, 5. 

In [ ]:
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


21. Write a NumPy program to compute sum of all elements, sum of each column and sum of each 

In [ ]:
x = np.array([[0,1],[2,3]])

print(x)

print(np.sum(x))

print(np.sum(x, axis=0))

print(np.sum(x, axis=1))

[[0 1]
 [2 3]]
6
[2 4]
[1 5]
